//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiBanco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteCuenta
    {
        public int id { get; set; }
        public int clienteId { get; set; }
        public int cuentaId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cuenta Cuenta { get; set; }
    }
}
